spring:
  application: 
    name: tensquare‐config
  cloud: 
    config: 
      server: 
        git: 
          uri: https://gitee.com/niudankuangren/tensquare.git
  rabbitmq: 
    host: 192.168.0.108   
    
management: 
  endpoints: 
    web: 
      exposure: 
        include: bus-refresh  

server:
  port: 12000

  
  

    

    