server: 
  port: 9009

spring: 
  application:
    name: tensquare-sms
  rabbitmq: 
    host:  192.168.0.108

aliyun:
  sms: 
    accessKeyId: LTAIWRCh9XLMiaml
    accessKeySecret: 010bjTqrczP8uTkN9jUZhNOHBqL0JW
    template_code: SMS_151233538
    sign_name: 品优购